apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: qdrant
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer