apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: qdrant
  labels:
    app: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      serviceAccountName: celery-pdf-worker  # Reuse existing service account
      containers:
        - name: query-service
          image: 705926388196.dkr.ecr.us-east-2.amazonaws.com/query-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 5000